//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Métadonnées de relation EDM

[assembly: EdmRelationshipAttribute("SIDatabaseModel", "FK_Hypothesis_Tickets", "Tickets", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SupportInvestigation.Models.Model.Ticket), "Hypothesis", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SupportInvestigation.Models.Model.Hypothesis), true)]
[assembly: EdmRelationshipAttribute("SIDatabaseModel", "FK_Tickets_Marchands", "Marchands", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SupportInvestigation.Models.Model.Marchand), "Tickets", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SupportInvestigation.Models.Model.Ticket), true)]
[assembly: EdmRelationshipAttribute("SIDatabaseModel", "FK_Tickets_Users", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SupportInvestigation.Models.Model.User), "Ticket", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SupportInvestigation.Models.Model.Ticket), true)]
[assembly: EdmRelationshipAttribute("SIDatabaseModel", "FK_Hypothesis_Users", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SupportInvestigation.Models.Model.User), "Hypothesis", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SupportInvestigation.Models.Model.Hypothesis), true)]

#endregion

namespace SupportInvestigation.Models.Model
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class SIDatabaseEntities : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet SIDatabaseEntities à l'aide de la chaîne de connexion trouvée dans la section 'SIDatabaseEntities' du fichier de configuration d'application.
        /// </summary>
        public SIDatabaseEntities() : base("name=SIDatabaseEntities", "SIDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet SIDatabaseEntities.
        /// </summary>
        public SIDatabaseEntities(string connectionString) : base(connectionString, "SIDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet SIDatabaseEntities.
        /// </summary>
        public SIDatabaseEntities(EntityConnection connection) : base(connection, "SIDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Hypothesis> Hypothesis
        {
            get
            {
                if ((_Hypothesis == null))
                {
                    _Hypothesis = base.CreateObjectSet<Hypothesis>("Hypothesis");
                }
                return _Hypothesis;
            }
        }
        private ObjectSet<Hypothesis> _Hypothesis;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Marchand> Marchands
        {
            get
            {
                if ((_Marchands == null))
                {
                    _Marchands = base.CreateObjectSet<Marchand>("Marchands");
                }
                return _Marchands;
            }
        }
        private ObjectSet<Marchand> _Marchands;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Ticket> Tickets
        {
            get
            {
                if ((_Tickets == null))
                {
                    _Tickets = base.CreateObjectSet<Ticket>("Tickets");
                }
                return _Tickets;
            }
        }
        private ObjectSet<Ticket> _Tickets;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion
        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Hypothesis. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToHypothesis(Hypothesis hypothesis)
        {
            base.AddObject("Hypothesis", hypothesis);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Marchands. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToMarchands(Marchand marchand)
        {
            base.AddObject("Marchands", marchand);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet sysdiagrams. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Tickets. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToTickets(Ticket ticket)
        {
            base.AddObject("Tickets", ticket);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Users. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion
    }
    

    #endregion
    
    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SIDatabaseModel", Name="Hypothesis")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Hypothesis : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Hypothesis.
        /// </summary>
        /// <param name="hypothesisID">Valeur initiale de la propriété hypothesisID.</param>
        /// <param name="title">Valeur initiale de la propriété title.</param>
        /// <param name="dateCreation">Valeur initiale de la propriété DateCreation.</param>
        /// <param name="stateSolved">Valeur initiale de la propriété StateSolved.</param>
        /// <param name="contents">Valeur initiale de la propriété Contents.</param>
        /// <param name="iDTicket">Valeur initiale de la propriété IDTicket.</param>
        public static Hypothesis CreateHypothesis(global::System.Int32 hypothesisID, global::System.String title, global::System.DateTime dateCreation, global::System.Int32 stateSolved, global::System.String contents, global::System.Int32 iDTicket)
        {
            Hypothesis hypothesis = new Hypothesis();
            hypothesis.hypothesisID = hypothesisID;
            hypothesis.title = title;
            hypothesis.DateCreation = dateCreation;
            hypothesis.StateSolved = stateSolved;
            hypothesis.Contents = contents;
            hypothesis.IDTicket = iDTicket;
            return hypothesis;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 hypothesisID
        {
            get
            {
                return _hypothesisID;
            }
            set
            {
                if (_hypothesisID != value)
                {
                    OnhypothesisIDChanging(value);
                    ReportPropertyChanging("hypothesisID");
                    _hypothesisID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("hypothesisID");
                    OnhypothesisIDChanged();
                }
            }
        }
        private global::System.Int32 _hypothesisID;
        partial void OnhypothesisIDChanging(global::System.Int32 value);
        partial void OnhypothesisIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreation
        {
            get
            {
                return _DateCreation;
            }
            set
            {
                OnDateCreationChanging(value);
                ReportPropertyChanging("DateCreation");
                _DateCreation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreation");
                OnDateCreationChanged();
            }
        }
        private global::System.DateTime _DateCreation;
        partial void OnDateCreationChanging(global::System.DateTime value);
        partial void OnDateCreationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateModification
        {
            get
            {
                return _DateModification;
            }
            set
            {
                OnDateModificationChanging(value);
                ReportPropertyChanging("DateModification");
                _DateModification = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateModification");
                OnDateModificationChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateModification;
        partial void OnDateModificationChanging(Nullable<global::System.DateTime> value);
        partial void OnDateModificationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StateSolved
        {
            get
            {
                return _StateSolved;
            }
            set
            {
                OnStateSolvedChanging(value);
                ReportPropertyChanging("StateSolved");
                _StateSolved = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StateSolved");
                OnStateSolvedChanged();
            }
        }
        private global::System.Int32 _StateSolved;
        partial void OnStateSolvedChanging(global::System.Int32 value);
        partial void OnStateSolvedChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Contents
        {
            get
            {
                return _Contents;
            }
            set
            {
                OnContentsChanging(value);
                ReportPropertyChanging("Contents");
                _Contents = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Contents");
                OnContentsChanged();
            }
        }
        private global::System.String _Contents;
        partial void OnContentsChanging(global::System.String value);
        partial void OnContentsChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDTicket
        {
            get
            {
                return _IDTicket;
            }
            set
            {
                OnIDTicketChanging(value);
                ReportPropertyChanging("IDTicket");
                _IDTicket = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDTicket");
                OnIDTicketChanged();
            }
        }
        private global::System.Int32 _IDTicket;
        partial void OnIDTicketChanging(global::System.Int32 value);
        partial void OnIDTicketChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDUser
        {
            get
            {
                return _IDUser;
            }
            set
            {
                OnIDUserChanging(value);
                ReportPropertyChanging("IDUser");
                _IDUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDUser");
                OnIDUserChanged();
            }
        }
        private Nullable<global::System.Int32> _IDUser;
        partial void OnIDUserChanging(Nullable<global::System.Int32> value);
        partial void OnIDUserChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SIDatabaseModel", "FK_Hypothesis_Tickets", "Tickets")]
        public Ticket Tickets
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ticket>("SIDatabaseModel.FK_Hypothesis_Tickets", "Tickets").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ticket>("SIDatabaseModel.FK_Hypothesis_Tickets", "Tickets").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Ticket> TicketsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ticket>("SIDatabaseModel.FK_Hypothesis_Tickets", "Tickets");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Ticket>("SIDatabaseModel.FK_Hypothesis_Tickets", "Tickets", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SIDatabaseModel", "FK_Hypothesis_Users", "User")]
        public User Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("SIDatabaseModel.FK_Hypothesis_Users", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("SIDatabaseModel.FK_Hypothesis_Users", "User").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("SIDatabaseModel.FK_Hypothesis_Users", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("SIDatabaseModel.FK_Hypothesis_Users", "User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SIDatabaseModel", Name="Marchand")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Marchand : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Marchand.
        /// </summary>
        /// <param name="marchandID">Valeur initiale de la propriété MarchandID.</param>
        /// <param name="name">Valeur initiale de la propriété Name.</param>
        /// <param name="url">Valeur initiale de la propriété Url.</param>
        /// <param name="contactName">Valeur initiale de la propriété ContactName.</param>
        /// <param name="phone">Valeur initiale de la propriété Phone.</param>
        public static Marchand CreateMarchand(global::System.Int32 marchandID, global::System.String name, global::System.String url, global::System.String contactName, global::System.Int32 phone)
        {
            Marchand marchand = new Marchand();
            marchand.MarchandID = marchandID;
            marchand.Name = name;
            marchand.Url = url;
            marchand.ContactName = contactName;
            marchand.Phone = phone;
            return marchand;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MarchandID
        {
            get
            {
                return _MarchandID;
            }
            set
            {
                if (_MarchandID != value)
                {
                    OnMarchandIDChanging(value);
                    ReportPropertyChanging("MarchandID");
                    _MarchandID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MarchandID");
                    OnMarchandIDChanged();
                }
            }
        }
        private global::System.Int32 _MarchandID;
        partial void OnMarchandIDChanging(global::System.Int32 value);
        partial void OnMarchandIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ContactName
        {
            get
            {
                return _ContactName;
            }
            set
            {
                OnContactNameChanging(value);
                ReportPropertyChanging("ContactName");
                _ContactName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ContactName");
                OnContactNameChanged();
            }
        }
        private global::System.String _ContactName;
        partial void OnContactNameChanging(global::System.String value);
        partial void OnContactNameChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.Int32 _Phone;
        partial void OnPhoneChanging(global::System.Int32 value);
        partial void OnPhoneChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SIDatabaseModel", "FK_Tickets_Marchands", "Tickets")]
        public EntityCollection<Ticket> Tickets
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ticket>("SIDatabaseModel.FK_Tickets_Marchands", "Tickets");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ticket>("SIDatabaseModel.FK_Tickets_Marchands", "Tickets", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SIDatabaseModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet sysdiagrams.
        /// </summary>
        /// <param name="name">Valeur initiale de la propriété name.</param>
        /// <param name="principal_id">Valeur initiale de la propriété principal_id.</param>
        /// <param name="diagram_id">Valeur initiale de la propriété diagram_id.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SIDatabaseModel", Name="Ticket")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ticket : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Ticket.
        /// </summary>
        /// <param name="ticketID">Valeur initiale de la propriété TicketID.</param>
        /// <param name="title">Valeur initiale de la propriété Title.</param>
        /// <param name="stateSolved">Valeur initiale de la propriété StateSolved.</param>
        /// <param name="stateRead">Valeur initiale de la propriété stateRead.</param>
        /// <param name="dateCreation">Valeur initiale de la propriété DateCreation.</param>
        /// <param name="dateModification">Valeur initiale de la propriété DateModification.</param>
        /// <param name="summary">Valeur initiale de la propriété Summary.</param>
        /// <param name="contents">Valeur initiale de la propriété Contents.</param>
        /// <param name="iDMarchand">Valeur initiale de la propriété IDMarchand.</param>
        /// <param name="iDUser">Valeur initiale de la propriété IDUser.</param>
        public static Ticket CreateTicket(global::System.Int32 ticketID, global::System.String title, global::System.Int32 stateSolved, global::System.Int32 stateRead, global::System.DateTime dateCreation, global::System.DateTime dateModification, global::System.String summary, global::System.String contents, global::System.Int32 iDMarchand, global::System.Int32 iDUser)
        {
            Ticket ticket = new Ticket();
            ticket.TicketID = ticketID;
            ticket.Title = title;
            ticket.StateSolved = stateSolved;
            ticket.stateRead = stateRead;
            ticket.DateCreation = dateCreation;
            ticket.DateModification = dateModification;
            ticket.Summary = summary;
            ticket.Contents = contents;
            ticket.IDMarchand = iDMarchand;
            ticket.IDUser = iDUser;
            return ticket;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TicketID
        {
            get
            {
                return _TicketID;
            }
            set
            {
                if (_TicketID != value)
                {
                    OnTicketIDChanging(value);
                    ReportPropertyChanging("TicketID");
                    _TicketID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TicketID");
                    OnTicketIDChanged();
                }
            }
        }
        private global::System.Int32 _TicketID;
        partial void OnTicketIDChanging(global::System.Int32 value);
        partial void OnTicketIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StateSolved
        {
            get
            {
                return _StateSolved;
            }
            set
            {
                OnStateSolvedChanging(value);
                ReportPropertyChanging("StateSolved");
                _StateSolved = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StateSolved");
                OnStateSolvedChanged();
            }
        }
        private global::System.Int32 _StateSolved;
        partial void OnStateSolvedChanging(global::System.Int32 value);
        partial void OnStateSolvedChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 stateRead
        {
            get
            {
                return _stateRead;
            }
            set
            {
                OnstateReadChanging(value);
                ReportPropertyChanging("stateRead");
                _stateRead = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("stateRead");
                OnstateReadChanged();
            }
        }
        private global::System.Int32 _stateRead;
        partial void OnstateReadChanging(global::System.Int32 value);
        partial void OnstateReadChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreation
        {
            get
            {
                return _DateCreation;
            }
            set
            {
                OnDateCreationChanging(value);
                ReportPropertyChanging("DateCreation");
                _DateCreation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreation");
                OnDateCreationChanged();
            }
        }
        private global::System.DateTime _DateCreation;
        partial void OnDateCreationChanging(global::System.DateTime value);
        partial void OnDateCreationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateModification
        {
            get
            {
                return _DateModification;
            }
            set
            {
                OnDateModificationChanging(value);
                ReportPropertyChanging("DateModification");
                _DateModification = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateModification");
                OnDateModificationChanged();
            }
        }
        private global::System.DateTime _DateModification;
        partial void OnDateModificationChanging(global::System.DateTime value);
        partial void OnDateModificationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Summary
        {
            get
            {
                return _Summary;
            }
            set
            {
                OnSummaryChanging(value);
                ReportPropertyChanging("Summary");
                _Summary = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Summary");
                OnSummaryChanged();
            }
        }
        private global::System.String _Summary;
        partial void OnSummaryChanging(global::System.String value);
        partial void OnSummaryChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Contents
        {
            get
            {
                return _Contents;
            }
            set
            {
                OnContentsChanging(value);
                ReportPropertyChanging("Contents");
                _Contents = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Contents");
                OnContentsChanged();
            }
        }
        private global::System.String _Contents;
        partial void OnContentsChanging(global::System.String value);
        partial void OnContentsChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDMarchand
        {
            get
            {
                return _IDMarchand;
            }
            set
            {
                OnIDMarchandChanging(value);
                ReportPropertyChanging("IDMarchand");
                _IDMarchand = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDMarchand");
                OnIDMarchandChanged();
            }
        }
        private global::System.Int32 _IDMarchand;
        partial void OnIDMarchandChanging(global::System.Int32 value);
        partial void OnIDMarchandChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDUser
        {
            get
            {
                return _IDUser;
            }
            set
            {
                OnIDUserChanging(value);
                ReportPropertyChanging("IDUser");
                _IDUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDUser");
                OnIDUserChanged();
            }
        }
        private global::System.Int32 _IDUser;
        partial void OnIDUserChanging(global::System.Int32 value);
        partial void OnIDUserChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SIDatabaseModel", "FK_Hypothesis_Tickets", "Hypothesis")]
        public EntityCollection<Hypothesis> Hypothesis
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Hypothesis>("SIDatabaseModel.FK_Hypothesis_Tickets", "Hypothesis");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Hypothesis>("SIDatabaseModel.FK_Hypothesis_Tickets", "Hypothesis", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SIDatabaseModel", "FK_Tickets_Marchands", "Marchands")]
        public Marchand Marchands
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Marchand>("SIDatabaseModel.FK_Tickets_Marchands", "Marchands").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Marchand>("SIDatabaseModel.FK_Tickets_Marchands", "Marchands").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Marchand> MarchandsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Marchand>("SIDatabaseModel.FK_Tickets_Marchands", "Marchands");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Marchand>("SIDatabaseModel.FK_Tickets_Marchands", "Marchands", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SIDatabaseModel", "FK_Tickets_Users", "Users")]
        public User Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("SIDatabaseModel.FK_Tickets_Users", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("SIDatabaseModel.FK_Tickets_Users", "Users").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("SIDatabaseModel.FK_Tickets_Users", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("SIDatabaseModel.FK_Tickets_Users", "Users", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SIDatabaseModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet User.
        /// </summary>
        /// <param name="userID">Valeur initiale de la propriété UserID.</param>
        /// <param name="login">Valeur initiale de la propriété Login.</param>
        /// <param name="password">Valeur initiale de la propriété Password.</param>
        /// <param name="mail">Valeur initiale de la propriété Mail.</param>
        /// <param name="level">Valeur initiale de la propriété Level.</param>
        public static User CreateUser(global::System.Int32 userID, global::System.String login, global::System.String password, global::System.String mail, global::System.Int32 level)
        {
            User user = new User();
            user.UserID = userID;
            user.Login = login;
            user.Password = password;
            user.Mail = mail;
            user.Level = level;
            return user;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Login
        {
            get
            {
                return _Login;
            }
            set
            {
                OnLoginChanging(value);
                ReportPropertyChanging("Login");
                _Login = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Login");
                OnLoginChanged();
            }
        }
        private global::System.String _Login;
        partial void OnLoginChanging(global::System.String value);
        partial void OnLoginChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Mail
        {
            get
            {
                return _Mail;
            }
            set
            {
                OnMailChanging(value);
                ReportPropertyChanging("Mail");
                _Mail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Mail");
                OnMailChanged();
            }
        }
        private global::System.String _Mail;
        partial void OnMailChanging(global::System.String value);
        partial void OnMailChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Level
        {
            get
            {
                return _Level;
            }
            set
            {
                OnLevelChanging(value);
                ReportPropertyChanging("Level");
                _Level = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Level");
                OnLevelChanged();
            }
        }
        private global::System.Int32 _Level;
        partial void OnLevelChanging(global::System.Int32 value);
        partial void OnLevelChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SIDatabaseModel", "FK_Tickets_Users", "Ticket")]
        public EntityCollection<Ticket> Tickets
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ticket>("SIDatabaseModel.FK_Tickets_Users", "Ticket");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ticket>("SIDatabaseModel.FK_Tickets_Users", "Ticket", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SIDatabaseModel", "FK_Hypothesis_Users", "Hypothesis")]
        public EntityCollection<Hypothesis> Hypothesis
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Hypothesis>("SIDatabaseModel.FK_Hypothesis_Users", "Hypothesis");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Hypothesis>("SIDatabaseModel.FK_Hypothesis_Users", "Hypothesis", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
